# ESO Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.external-secrets.io"
    chart: external-secrets
    targetRevision: 0.9.19
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# BankApp Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/karty11/Github-Actions-Project.git'
    targetRevision: main
    path: helm/bankapp-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: devproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
