
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/karty11/your-repo.git'
    targetRevision: main
    path: helm/bankapp-chart
    helm:
      parameters:
        - name: image.repository
          value: karty11/newbankapp
        - name: image.tag
          value: {{ .Values.image.tag | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: devproject
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
