apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: devproject
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: {{ .Values.mysql.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: bankapp/mysql-root-password
