replicaCount: 1

image:
  repository: karty11/newbankapp
  tag: latest

mysql:
  database: "bankappdb"
  user: "root"
  secretName: "mysql-secret"

service:
  type: LoadBalancer
  port: 80

resources: {}
