apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # 🚀 install ESO first
spec:
  project: default
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.13   # latest stable release
    helm:
      parameters:
        - name: installCRDs
          value: "true"       # 👈 ensures CRDs are installed
      values: |
        serviceAccount:
          create: false
          name: external-secrets   # reuse IRSA service account from Terraform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
