apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankapp-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/karty11/Github-Actions-Project.git'
    targetRevision: main
    path: helm/manifests/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: bankapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
