apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/karty11/Github-Actions-Project.git
    targetRevision: main
    path: helm/applications       
    directory:
      recurse: true               
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
