apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: bankapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mysql-secret
        property: username
    - secretKey: password
      remoteRef:
        key: mysql-secret
        property: password
