name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy_to_kubernetes:
    runs-on: self-hosted
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.EKS_KUBECONFIG }}" > $HOME/.kube/config

      - name: Install ArgoCD
        run: |
           kubectl create namespace argocd || true
           kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
           kubectl rollout status deployment/argocd-server -n argocd

      - name: Wait for ArgoCD to be Ready
        run: |
         kubectl rollout status deployment/argocd-application-controller -n argocd --timeout=180s
         kubectl rollout status deployment/argocd-repo-server -n argocd --timeout=180s
         kubectl rollout status deployment/argocd-server -n argocd --timeout=180s

      - name: Apply ESO ArgoCD Application
        run: |
          kubectl apply -f helm/applications/eso-application.yaml
          kubectl -n argocd wait application/external-secrets --for condition=Synced --timeout=600s

      - name: Apply BankApp ArgoCD Application
        run: |
          kubectl apply -f helm/applications/bankapp-application.yaml
          kubectl -n argocd wait application/bankapp --for condition=Synced --timeout=600s
